// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Car struct {
	ID          pgtype.UUID      `json:"id"`
	Name        pgtype.Text      `json:"name"`
	Color       pgtype.Text      `json:"color"`
	NumberPlate pgtype.Text      `json:"number_plate"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Deliver struct {
	ID            pgtype.UUID      `json:"id"`
	Name          string           `json:"name"`
	Email         string           `json:"email"`
	Password      string           `json:"password"`
	LicenseNumber pgtype.Text      `json:"license_number"`
	NationalID    pgtype.Text      `json:"national_id"`
	CarID         pgtype.UUID      `json:"car_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type DriverLocation struct {
	ID        pgtype.UUID      `json:"id"`
	DriverID  pgtype.UUID      `json:"driver_id"`
	OrderID   pgtype.UUID      `json:"order_id"`
	Latitude  pgtype.Numeric   `json:"latitude"`
	Longitude pgtype.Numeric   `json:"longitude"`
	Heading   pgtype.Float8    `json:"heading"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Order struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	DeliverID       pgtype.UUID      `json:"deliver_id"`
	RestaurantID    pgtype.UUID      `json:"restaurant_id"`
	TotalPrice      pgtype.Numeric   `json:"total_price"`
	PickupLocation  pgtype.Text      `json:"pickup_location"`
	DropoffLocation pgtype.Text      `json:"dropoff_location"`
	Status          pgtype.Text      `json:"status"`
	ShippedAt       pgtype.Timestamp `json:"shipped_at"`
	DeliveredAt     pgtype.Timestamp `json:"delivered_at"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type OrderItem struct {
	ID              pgtype.UUID    `json:"id"`
	OrderID         pgtype.UUID    `json:"order_id"`
	ProductID       pgtype.UUID    `json:"product_id"`
	Quantity        int32          `json:"quantity"`
	PriceAtPurchase pgtype.Numeric `json:"price_at_purchase"`
	Image           pgtype.Text    `json:"image"`
}

type Payment struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	OrderID   pgtype.UUID      `json:"order_id"`
	Amount    pgtype.Numeric   `json:"amount"`
	Discount  pgtype.Numeric   `json:"discount"`
	Total     pgtype.Numeric   `json:"total"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Product struct {
	ID            pgtype.UUID      `json:"id"`
	RestaurantID  pgtype.UUID      `json:"restaurant_id"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	Price         pgtype.Numeric   `json:"price"`
	Category      pgtype.Text      `json:"category"`
	Images        []string         `json:"images"`
	StockQuantity pgtype.Int4      `json:"stock_quantity"`
	AverageRating pgtype.Float8    `json:"average_rating"`
	TotalReviews  pgtype.Int4      `json:"total_reviews"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type ResAddress struct {
	ID           pgtype.UUID      `json:"id"`
	RestaurantID pgtype.UUID      `json:"restaurant_id"`
	StreetName   pgtype.Text      `json:"street_name"`
	City         pgtype.Text      `json:"city"`
	State        pgtype.Text      `json:"state"`
	Phone        pgtype.Text      `json:"phone"`
	Email        pgtype.Text      `json:"email"`
	IsDefault    pgtype.Bool      `json:"is_default"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Restaurant struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	Password     string           `json:"password"`
	PhoneNumber  pgtype.Text      `json:"phone_number"`
	ImageUrl     pgtype.Text      `json:"image_url"`
	RestaurantID pgtype.UUID      `json:"restaurant_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type UserAddress struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	City      pgtype.Text      `json:"city"`
	State     pgtype.Text      `json:"state"`
	ZipCode   pgtype.Text      `json:"zip_code"`
	IsDefault pgtype.Bool      `json:"is_default"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
