// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPassword = `-- name: CheckPassword :one
SELECT id, name, email, password FROM users WHERE email = $1
`

type CheckPasswordRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
}

func (q *Queries) CheckPassword(ctx context.Context, email string) (CheckPasswordRow, error) {
	row := q.db.QueryRow(ctx, checkPassword, email)
	var i CheckPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getUserList = `-- name: GetUserList :many
SELECT id, name, email, password, phone_number, image_url, restaurant_id, created_at, updated_at FROM users ORDER BY name
`

func (q *Queries) GetUserList(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUserList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.PhoneNumber,
			&i.ImageUrl,
			&i.RestaurantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newUser = `-- name: NewUser :one
INSERT INTO users (
  name,
  email,
  password,
  phone_number,
  image_url,
  restaurant_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
) RETURNING id, name, email, password, phone_number, image_url, restaurant_id, created_at, updated_at
`

type NewUserParams struct {
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	Password     string      `json:"password"`
	PhoneNumber  pgtype.Text `json:"phone_number"`
	ImageUrl     pgtype.Text `json:"image_url"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) NewUser(ctx context.Context, arg NewUserParams) (User, error) {
	row := q.db.QueryRow(ctx, newUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.ImageUrl,
		arg.RestaurantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.ImageUrl,
		&i.RestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
