// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getUserList = `-- name: GetUserList :many
SELECT id, name, email, password, phone_number, image_url, restaurant_id, created_at, updated_at FROM users ORDER BY name
`

func (q *Queries) GetUserList(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUserList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.PhoneNumber,
			&i.ImageUrl,
			&i.RestaurantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
